In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('./Data/datapoints.csv')  
df.head()

,customer_id,Name,age,gender,security_no,region_category,membership_category,joining_date,joined_through_referral,referral_id,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,fffe4300490044003600300030003800,Pattie Morrisey,18,F,XW0DQ7H,Village,Platinum Membership,2017-08-17,No,xxxxxxxx,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,fffe43004900440032003100300035003700,Traci Peery,32,F,5K0N3X1,City,Premium Membership,2017-08-28,?,CID21329,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,1
2,fffe4300490044003100390032003600,Merideth Mcmeen,44,F,1F2TCL3,Town,No Membership,2016-11-11,Yes,CID12313,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,fffe43004900440036003000330031003600,Eufemia Cardwell,37,M,VJGJ33N,City,No Membership,2016-10-29,Yes,CID3793,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,5
4,fffe43004900440031003900350030003600,Meghan Kosak,31,F,SVZXCWB,City,No Membership,2017-09-12,No,xxxxxxxx,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,5

In [3]:
df.drop(['customer_id',"Name","security_no","referral_id"], axis=1, inplace=True)

In [4]:
df.head()

,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,last_visit_time,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,F,Village,Platinum Membership,2017-08-17,No,Gift Vouchers/Coupons,?,Wi-Fi,16:08:02,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,F,City,Premium Membership,2017-08-28,?,Gift Vouchers/Coupons,Desktop,Mobile_Data,12:38:13,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,F,Town,No Membership,2016-11-11,Yes,Gift Vouchers/Coupons,Desktop,Wi-Fi,22:53:21,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,M,City,No Membership,2016-10-29,Yes,Gift Vouchers/Coupons,Desktop,Mobile_Data,15:57:50,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,5
4,31,F,City,No Membership,2017-09-12,No,Credit/Debit Card Offers,Smartphone,Mobile_Data,15:46:44,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,5

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36992 non-null  object
 2   region_category               31564 non-null  object
 3   membership_category           36992 non-null  object
 4   joining_date                  36992 non-null  object
 5   joined_through_referral       36992 non-null  object
 6   preferred_offer_types         36704 non-null  object
 7   medium_of_operation           36992 non-null  object
 8   internet_option               36992 non-null  object
 9   last_visit_time               36992 non-null  object
 10  days_since_last_login         36992 non-null  int64
 11  avg_time_spent                36992 non-null  float64
 12  avg_transaction_value         36992 non-null  float64
 13  avg_frequency_login_days      36992 non-null  object
 14  points_in_wallet              33549 non-null  float64
 15  used_special_discount         36992 non-null  object
 16  offer_application_preference  36992 non-null  object
 17  past_complaint                36992 non-null  object
 18  complaint_status              36992 non-null  object
 19  feedback                      36992 non-null  object
 20  churn_risk_score              36992 non-null  int64
dtypes: float64(3), int64(3), object(15)
memory usage: 5.9+ MB

In [6]:
df['gender']=df['gender'].map({'M':1,'F':0})

In [7]:
df['gender'].isna().sum()
df['gender'].fillna(df['gender'].mode()[0],inplace=True)

C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\1323894353.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0],inplace=True)

In [8]:
df['joined_through_referral'].isnull().sum()

np.int64(0)

In [9]:
df['joined_through_referral'].unique()

array(['No', '?', 'Yes'], dtype=object)

In [10]:
df["joined_through_referral"]=df["joined_through_referral"].map({'Yes':1,'No':0,'?':np.nan})

In [11]:
df['joined_through_referral'].fillna(df['joined_through_referral'].mode()[0],inplace=True)

C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\3044584991.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['joined_through_referral'].fillna(df['joined_through_referral'].mode()[0],inplace=True)

In [12]:
df['joined_through_referral'].isna().sum()

np.int64(0)

In [13]:
df.head()

,age,gender,region_category,membership_category,joining_date,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,last_visit_time,...,avg_time_spent,avg_transaction_value,avg_frequency_login_days,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score
0,18,0.0,Village,Platinum Membership,2017-08-17,0.0,Gift Vouchers/Coupons,?,Wi-Fi,16:08:02,...,300.63,53005.25,17.0,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2
1,32,0.0,City,Premium Membership,2017-08-28,0.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,12:38:13,...,306.34,12838.38,10.0,NaN,Yes,No,Yes,Solved,Quality Customer Care,1
2,44,0.0,Town,No Membership,2016-11-11,1.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,22:53:21,...,516.16,21027.00,22.0,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5
3,37,1.0,City,No Membership,2016-10-29,1.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,15:57:50,...,53.27,25239.56,6.0,567.66,No,Yes,Yes,Unsolved,Poor Website,5
4,31,0.0,City,No Membership,2017-09-12,0.0,Credit/Debit Card Offers,Smartphone,Mobile_Data,15:46:44,...,113.13,24483.66,16.0,663.06,No,Yes,Yes,Solved,Poor Website,5

In [14]:
df['region_category'].unique()

array(['Village', 'City', 'Town', nan], dtype=object)

In [15]:
df['region_category'].isna().sum()
df['region_category'].fillna(df['region_category'].mode()[0],inplace=True)

C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\3328088867.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['region_category'].fillna(df['region_category'].mode()[0],inplace=True)

In [16]:
df['region_category'].isna().sum()

np.int64(0)

In [17]:
df['membership_category'].unique()

array(['Platinum Membership', 'Premium Membership', 'No Membership',
       'Gold Membership', 'Silver Membership', 'Basic Membership'],
      dtype=object)

In [18]:
df["joining_year"]=df["joining_date"].apply(lambda x: int(x.split('-')[0]))
df["joining_month"]=df["joining_date"].apply(lambda x: int(x.split('-')[1]))
df["joining_day"]=df["joining_date"].apply(lambda x: int(x.split('-')[2]))

In [19]:
df.drop(['joining_date'], axis=1, inplace=True)

In [20]:
df["preferred_offer_types"].unique()

array(['Gift Vouchers/Coupons', 'Credit/Debit Card Offers',
       'Without Offers', nan], dtype=object)

In [21]:
df['preferred_offer_types'].fillna(df['preferred_offer_types'].mode()[0],inplace=True)

C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\2997640742.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['preferred_offer_types'].fillna(df['preferred_offer_types'].mode()[0],inplace=True)

In [22]:
df["preferred_offer_types"].unique()

array(['Gift Vouchers/Coupons', 'Credit/Debit Card Offers',
       'Without Offers'], dtype=object)

In [23]:
df['medium_of_operation'].unique()

array(['?', 'Desktop', 'Smartphone', 'Both'], dtype=object)

In [24]:
df['medium_of_operation'].isna().sum()

np.int64(0)

In [25]:


df['medium_of_operation'].replace({"?":df['medium_of_operation'].mode()[0]}, inplace=True)

C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\2133802712.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['medium_of_operation'].replace({"?":df['medium_of_operation'].mode()[0]}, inplace=True)

In [26]:
df['medium_of_operation'].unique()

array(['Desktop', 'Smartphone', 'Both'], dtype=object)

In [27]:
df.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,last_visit_time,days_since_last_login,...,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,joining_year,joining_month,joining_day
0,18,0.0,Village,Platinum Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,16:08:02,17,...,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2,2017,8,17
1,32,0.0,City,Premium Membership,0.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,12:38:13,16,...,NaN,Yes,No,Yes,Solved,Quality Customer Care,1,2017,8,28
2,44,0.0,Town,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,22:53:21,14,...,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5,2016,11,11
3,37,1.0,City,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,15:57:50,11,...,567.66,No,Yes,Yes,Unsolved,Poor Website,5,2016,10,29
4,31,0.0,City,No Membership,0.0,Credit/Debit Card Offers,Smartphone,Mobile_Data,15:46:44,20,...,663.06,No,Yes,Yes,Solved,Poor Website,5,2017,9,12

In [28]:
df["internet_option"].unique()
df["internet_option"].isna().sum()

np.int64(0)

In [29]:
df['last_visit_time'].isna().sum()

np.int64(0)

In [30]:
df.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,last_visit_time,days_since_last_login,...,points_in_wallet,used_special_discount,offer_application_preference,past_complaint,complaint_status,feedback,churn_risk_score,joining_year,joining_month,joining_day
0,18,0.0,Village,Platinum Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,16:08:02,17,...,781.75,Yes,Yes,No,Not Applicable,Products always in Stock,2,2017,8,17
1,32,0.0,City,Premium Membership,0.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,12:38:13,16,...,NaN,Yes,No,Yes,Solved,Quality Customer Care,1,2017,8,28
2,44,0.0,Town,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,22:53:21,14,...,500.69,No,Yes,Yes,Solved in Follow-up,Poor Website,5,2016,11,11
3,37,1.0,City,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,15:57:50,11,...,567.66,No,Yes,Yes,Unsolved,Poor Website,5,2016,10,29
4,31,0.0,City,No Membership,0.0,Credit/Debit Card Offers,Smartphone,Mobile_Data,15:46:44,20,...,663.06,No,Yes,Yes,Solved,Poor Website,5,2017,9,12

In [31]:
df["last_visit_hour"]=df["last_visit_time"].apply(lambda x: int(x.split(':')[0]))
df["last_visit_min"]=df["last_visit_time"].apply(lambda x: int(x.split(':')[1]))
df["last_visit_second"]=df["last_visit_time"].apply(lambda x: int(x.split(':')[2]))
df.drop(['last_visit_time'], axis=1, inplace=True)

In [32]:
df.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,...,past_complaint,complaint_status,feedback,churn_risk_score,joining_year,joining_month,joining_day,last_visit_hour,last_visit_min,last_visit_second
0,18,0.0,Village,Platinum Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,...,No,Not Applicable,Products always in Stock,2,2017,8,17,16,8,2
1,32,0.0,City,Premium Membership,0.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,16,306.34,...,Yes,Solved,Quality Customer Care,1,2017,8,28,12,38,13
2,44,0.0,Town,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,...,Yes,Solved in Follow-up,Poor Website,5,2016,11,11,22,53,21
3,37,1.0,City,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,...,Yes,Unsolved,Poor Website,5,2016,10,29,15,57,50
4,31,0.0,City,No Membership,0.0,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,...,Yes,Solved,Poor Website,5,2017,9,12,15,46,44

In [33]:
df['days_since_last_login'].isna().sum()

np.int64(0)

In [34]:
df['avg_time_spent'].isna().sum()

np.int64(0)

In [35]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36992 entries, 0 to 36991
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           36992 non-null  int64
 1   gender                        36992 non-null  float64
 2   region_category               36992 non-null  object
 3   membership_category           36992 non-null  object
 4   joined_through_referral       36992 non-null  float64
 5   preferred_offer_types         36992 non-null  object
 6   medium_of_operation           36992 non-null  object
 7   internet_option               36992 non-null  object
 8   days_since_last_login         36992 non-null  int64
 9   avg_time_spent                36992 non-null  float64
 10  avg_transaction_value         36992 non-null  float64
 11  avg_frequency_login_days      36992 non-null  object
 12  points_in_wallet              33549 non-null  float64
 13  used_special_discount         36992 non-null  object
 14  offer_application_preference  36992 non-null  object
 15  past_complaint                36992 non-null  object
 16  complaint_status              36992 non-null  object
 17  feedback                      36992 non-null  object
 18  churn_risk_score              36992 non-null  int64
 19  joining_year                  36992 non-null  int64
 20  joining_month                 36992 non-null  int64
 21  joining_day                   36992 non-null  int64
 22  last_visit_hour               36992 non-null  int64
 23  last_visit_min                36992 non-null  int64
 24  last_visit_second             36992 non-null  int64
dtypes: float64(5), int64(9), object(11)
memory usage: 7.1+ MB
None

In [36]:
df['avg_transaction_value'].isna().sum()

np.int64(0)

In [37]:
df['avg_frequency_login_days'].isna().sum()

np.int64(0)

In [38]:
df['avg_frequency_login_days'] = pd.to_numeric(df['avg_frequency_login_days'], errors='coerce').astype(float)

In [39]:
df['points_in_wallet'].isna().sum()

np.int64(3443)

In [40]:
df = df[df['points_in_wallet'].notna()]

In [41]:
df['points_in_wallet'].isna().sum()

np.int64(0)

In [42]:
df.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,...,past_complaint,complaint_status,feedback,churn_risk_score,joining_year,joining_month,joining_day,last_visit_hour,last_visit_min,last_visit_second
0,18,0.0,Village,Platinum Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,...,No,Not Applicable,Products always in Stock,2,2017,8,17,16,8,2
2,44,0.0,Town,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,...,Yes,Solved in Follow-up,Poor Website,5,2016,11,11,22,53,21
3,37,1.0,City,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,...,Yes,Unsolved,Poor Website,5,2016,10,29,15,57,50
4,31,0.0,City,No Membership,0.0,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,...,Yes,Solved,Poor Website,5,2017,9,12,15,46,44
5,13,1.0,City,Gold Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,23,433.62,...,Yes,Unsolved,No reason specified,3,2016,1,8,6,46,7

In [43]:
df['used_special_discount'].unique()
df['used_special_discount'].isna().sum()
df['used_special_discount'] = df['used_special_discount'].map({'Yes':1,'No':0})

In [44]:
df['offer_application_preference'].unique() 
df['offer_application_preference'].isna().sum()
df['offer_application_preference'] = df['offer_application_preference'].map({'Yes':1,'No':0})

In [45]:
df['past_complaint'].unique()
df['past_complaint'].isna().sum()
df['past_complaint'] = df['past_complaint'].map({'Yes':1,'No':0})

In [46]:
df['complaint_status'].unique()

array(['Not Applicable', 'Solved in Follow-up', 'Unsolved', 'Solved',
       'No Information Available'], dtype=object)

In [47]:
df['complaint_status'].isna().sum()

np.int64(0)

In [48]:
df.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,...,past_complaint,complaint_status,feedback,churn_risk_score,joining_year,joining_month,joining_day,last_visit_hour,last_visit_min,last_visit_second
0,18,0.0,Village,Platinum Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,...,0,Not Applicable,Products always in Stock,2,2017,8,17,16,8,2
2,44,0.0,Town,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,...,1,Solved in Follow-up,Poor Website,5,2016,11,11,22,53,21
3,37,1.0,City,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,...,1,Unsolved,Poor Website,5,2016,10,29,15,57,50
4,31,0.0,City,No Membership,0.0,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,...,1,Solved,Poor Website,5,2017,9,12,15,46,44
5,13,1.0,City,Gold Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,23,433.62,...,1,Unsolved,No reason specified,3,2016,1,8,6,46,7

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33549 entries, 0 to 36991
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           33549 non-null  int64
 1   gender                        33549 non-null  float64
 2   region_category               33549 non-null  object
 3   membership_category           33549 non-null  object
 4   joined_through_referral       33549 non-null  float64
 5   preferred_offer_types         33549 non-null  object
 6   medium_of_operation           33549 non-null  object
 7   internet_option               33549 non-null  object
 8   days_since_last_login         33549 non-null  int64
 9   avg_time_spent                33549 non-null  float64
 10  avg_transaction_value         33549 non-null  float64
 11  avg_frequency_login_days      30352 non-null  float64
 12  points_in_wallet              33549 non-null  float64
 13  used_special_discount         33549 non-null  int64
 14  offer_application_preference  33549 non-null  int64
 15  past_complaint                33549 non-null  int64
 16  complaint_status              33549 non-null  object
 17  feedback                      33549 non-null  object
 18  churn_risk_score              33549 non-null  int64
 19  joining_year                  33549 non-null  int64
 20  joining_month                 33549 non-null  int64
 21  joining_day                   33549 non-null  int64
 22  last_visit_hour               33549 non-null  int64
 23  last_visit_min                33549 non-null  int64
 24  last_visit_second             33549 non-null  int64
dtypes: float64(6), int64(12), object(7)
memory usage: 6.7+ MB

In [50]:
lst=['avg_frequency_login_days',]

In [51]:
df.head()

,age,gender,region_category,membership_category,joined_through_referral,preferred_offer_types,medium_of_operation,internet_option,days_since_last_login,avg_time_spent,...,past_complaint,complaint_status,feedback,churn_risk_score,joining_year,joining_month,joining_day,last_visit_hour,last_visit_min,last_visit_second
0,18,0.0,Village,Platinum Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,17,300.63,...,0,Not Applicable,Products always in Stock,2,2017,8,17,16,8,2
2,44,0.0,Town,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,14,516.16,...,1,Solved in Follow-up,Poor Website,5,2016,11,11,22,53,21
3,37,1.0,City,No Membership,1.0,Gift Vouchers/Coupons,Desktop,Mobile_Data,11,53.27,...,1,Unsolved,Poor Website,5,2016,10,29,15,57,50
4,31,0.0,City,No Membership,0.0,Credit/Debit Card Offers,Smartphone,Mobile_Data,20,113.13,...,1,Solved,Poor Website,5,2017,9,12,15,46,44
5,13,1.0,City,Gold Membership,0.0,Gift Vouchers/Coupons,Desktop,Wi-Fi,23,433.62,...,1,Unsolved,No reason specified,3,2016,1,8,6,46,7

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33549 entries, 0 to 36991
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   age                           33549 non-null  int64
 1   gender                        33549 non-null  float64
 2   region_category               33549 non-null  object
 3   membership_category           33549 non-null  object
 4   joined_through_referral       33549 non-null  float64
 5   preferred_offer_types         33549 non-null  object
 6   medium_of_operation           33549 non-null  object
 7   internet_option               33549 non-null  object
 8   days_since_last_login         33549 non-null  int64
 9   avg_time_spent                33549 non-null  float64
 10  avg_transaction_value         33549 non-null  float64
 11  avg_frequency_login_days      30352 non-null  float64
 12  points_in_wallet              33549 non-null  float64
 13  used_special_discount         33549 non-null  int64
 14  offer_application_preference  33549 non-null  int64
 15  past_complaint                33549 non-null  int64
 16  complaint_status              33549 non-null  object
 17  feedback                      33549 non-null  object
 18  churn_risk_score              33549 non-null  int64
 19  joining_year                  33549 non-null  int64
 20  joining_month                 33549 non-null  int64
 21  joining_day                   33549 non-null  int64
 22  last_visit_hour               33549 non-null  int64
 23  last_visit_min                33549 non-null  int64
 24  last_visit_second             33549 non-null  int64
dtypes: float64(6), int64(12), object(7)
memory usage: 6.7+ MB

In [53]:
dict_uni={}
for col in df.columns:
    if df[col].dtype == 'object' and col!='feedback':
        dict_uni[col]=df[col].nunique()

In [54]:
dict_uni

{'region_category': 3,
 'membership_category': 6,
 'preferred_offer_types': 3,
 'medium_of_operation': 3,
 'internet_option': 3,
 'complaint_status': 5}

In [55]:
df['complaint_status'].unique()

array(['Not Applicable', 'Solved in Follow-up', 'Unsolved', 'Solved',
       'No Information Available'], dtype=object)

In [56]:
df['complaint_status']=df['complaint_status'].map({'Not Applicable':0,'Solved in Follow-up':1,'Unsolved':0,'Solved':1,'No Information Available':np.nan})

In [57]:
df['complaint_status'].isna().sum()
df['complaint_status'].fillna(df['complaint_status'].mode()[0],inplace=True)

C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\762593248.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['complaint_status'].fillna(df['complaint_status'].mode()[0],inplace=True)

In [58]:
dict_uni={}
for col in df.columns:
    if df[col].dtype == 'object' and col!='feedback':
        dict_uni[col]=df[col].nunique()

dict_uni

{'region_category': 3,
 'membership_category': 6,
 'preferred_offer_types': 3,
 'medium_of_operation': 3,
 'internet_option': 3}

In [59]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder( drop='first')
cat_cols=['region_category','membership_category','preferred_offer_types','medium_of_operation','internet_option']

In [60]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('onehot', ohe, cat_cols)], remainder='passthrough',verbose_feature_names_out=False)

In [61]:
from sklearn.model_selection import train_test_split
X=df.drop('churn_risk_score',axis=1)
y=df['churn_risk_score']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [62]:
x_train=ct.fit_transform(X_train)
x_test=x_test=ct.transform(X_test)
columns=ct.get_feature_names_out()

In [63]:
x_train=pd.DataFrame(x_train,columns=columns)
x_test=pd.DataFrame(x_test,columns=columns)

In [64]:
x_train

,region_category_Town,region_category_Village,membership_category_Gold Membership,membership_category_No Membership,membership_category_Platinum Membership,membership_category_Premium Membership,membership_category_Silver Membership,preferred_offer_types_Gift Vouchers/Coupons,preferred_offer_types_Without Offers,medium_of_operation_Desktop,...,offer_application_preference,past_complaint,complaint_status,feedback,joining_year,joining_month,joining_day,last_visit_hour,last_visit_min,last_visit_second
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,1,0.0,No reason specified,2016,4,8,12,51,39
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0,1,0.0,Poor Product Quality,2017,9,13,15,47,52
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0,1,0.0,Too many ads,2016,3,4,9,53,50
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,0,0.0,Poor Product Quality,2015,1,20,22,22,13
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0,0,0.0,No reason specified,2015,11,7,11,28,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23479,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1,0,0.0,Poor Product Quality,2017,9,2,22,13,31
23480,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1,0,0.0,Poor Product Quality,2017,4,29,15,16,10
23481,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1,0,0.0,Poor Customer Service,2015,2,22,18,44,1
23482,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0.0,Poor Website,2015,1,12,18,3,42
23483,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1,1,1.0,Poor Customer Service,2016,8,20,3,18,40

In [65]:
for col in x_train.columns:
    if x_train[col].dtype=='object' and col!='feedback':
        if x_train[col].isna().sum()>0:
            x_train[col].fillna(x_train[col].mode()[0],inplace=True)


for col in x_test.columns:
    if x_test[col].dtype=='object' and col!='feedback':
        if x_test[col].isna().sum()>0:
            x_test[col].fillna(x_test[col].mode()[0],inplace=True)

C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\3337445675.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_train[col].fillna(x_train[col].mode()[0],inplace=True)
C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\3337445675.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_train[col].fillna(x_train[col].mode()[0],inplace=True)
C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\3337445675.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_test[col].fillna(x_test[col].mode()[0],inplace=True)
C:\Users\sarth\AppData\Local\Temp\ipykernel_25644\3337445675.py:10: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_test[col].fillna(x_test[col].mode()[0],inplace=True)

In [66]:
for col in x_train.columns:
    if x_train[col].dtype=='object' and col!='feedback':
        x_train[col]=x_train[col].astype(float)
        x_test[col]=x_test[col].astype(float)

In [67]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23484 entries, 0 to 23483
Data columns (total 32 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   region_category_Town                         23484 non-null  float64
 1   region_category_Village                      23484 non-null  float64
 2   membership_category_Gold Membership          23484 non-null  float64
 3   membership_category_No Membership            23484 non-null  float64
 4   membership_category_Platinum Membership      23484 non-null  float64
 5   membership_category_Premium Membership       23484 non-null  float64
 6   membership_category_Silver Membership        23484 non-null  float64
 7   preferred_offer_types_Gift Vouchers/Coupons  23484 non-null  float64
 8   preferred_offer_types_Without Offers         23484 non-null  float64
 9   medium_of_operation_Desktop                  23484 non-null  float64
 10  medium_of_operation_Smartphone               23484 non-null  float64
 11  internet_option_Mobile_Data                  23484 non-null  float64
 12  internet_option_Wi-Fi                        23484 non-null  float64
 13  age                                          23484 non-null  float64
 14  gender                                       23484 non-null  float64
 15  joined_through_referral                      23484 non-null  float64
 16  days_since_last_login                        23484 non-null  float64
 17  avg_time_spent                               23484 non-null  float64
 18  avg_transaction_value                        23484 non-null  float64
 19  avg_frequency_login_days                     23484 non-null  float64
 20  points_in_wallet                             23484 non-null  float64
 21  used_special_discount                        23484 non-null  float64
 22  offer_application_preference                 23484 non-null  float64
 23  past_complaint                               23484 non-null  float64
 24  complaint_status                             23484 non-null  float64
 25  feedback                                     23484 non-null  object
 26  joining_year                                 23484 non-null  float64
 27  joining_month                                23484 non-null  float64
 28  joining_day                                  23484 non-null  float64
 29  last_visit_hour                              23484 non-null  float64
 30  last_visit_min                               23484 non-null  float64
 31  last_visit_second                            23484 non-null  float64
dtypes: float64(31), object(1)
memory usage: 5.7+ MB

In [68]:
x_train['feedback']=x_train['feedback'].str.lower()
x_test['feedback']=x_test['feedback'].str.lower()
import re

In [69]:
import nltk
from nltk.corpus import stopwords

In [ ]:
x_train['feedback']=x_train['feedback'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x)) 
## Remove the stopswords
x_train['feedback']=x_train['feedback'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
x_train['feedback']=x_train['feedback'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove any additional spaces
x_train['feedback']=x_train['feedback'].apply(lambda x: " ".join(x.split()))

In [70]:
x_test['feedback']=x_test['feedback'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x)) 
## Remove the stopswords
x_test['feedback']=x_test['feedback'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
x_test['feedback']=x_test['feedback'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove any additional spaces
x_test['feedback']=x_test['feedback'].apply(lambda x: " ".join(x.split()))

In [71]:
x_train

,region_category_Town,region_category_Village,membership_category_Gold Membership,membership_category_No Membership,membership_category_Platinum Membership,membership_category_Premium Membership,membership_category_Silver Membership,preferred_offer_types_Gift Vouchers/Coupons,preferred_offer_types_Without Offers,medium_of_operation_Desktop,...,offer_application_preference,past_complaint,complaint_status,feedback,joining_year,joining_month,joining_day,last_visit_hour,last_visit_min,last_visit_second
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,1.0,0.0,no reason specified,2016.0,4.0,8.0,12.0,51.0,39.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,1.0,0.0,poor product quality,2017.0,9.0,13.0,15.0,47.0,52.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,too many ads,2016.0,3.0,4.0,9.0,53.0,50.0
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.0,poor product quality,2015.0,1.0,20.0,22.0,22.0,13.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,no reason specified,2015.0,11.0,7.0,11.0,28.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23479,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,0.0,poor product quality,2017.0,9.0,2.0,22.0,13.0,31.0
23480,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,poor product quality,2017.0,4.0,29.0,15.0,16.0,10.0
23481,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,0.0,poor customer service,2015.0,2.0,22.0,18.0,44.0,1.0
23482,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,poor website,2015.0,1.0,12.0,18.0,3.0,42.0
23483,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,1.0,poor customer service,2016.0,8.0,20.0,3.0,18.0,40.0

In [72]:

import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [73]:
# Function to convert text to average word vector
def text_to_vector(text, model):
    words = text.split()
    word_vectors = []
    
    for word in words:
        if word in model:
            word_vectors.append(model[word])
    
    if len(word_vectors) == 0:
        return np.zeros(300)  # Return zero vector if no words found
    
    return np.mean(word_vectors, axis=0)

In [74]:
# Apply to train and test sets
x_train_feedback_vectors = x_train['feedback'].apply(lambda x: text_to_vector(x, wv))
x_test_feedback_vectors = x_test['feedback'].apply(lambda x: text_to_vector(x, wv))

In [75]:
# Convert to DataFrame with column names
feedback_train_df = pd.DataFrame(x_train_feedback_vectors.tolist(), 
                                  columns=[f'feedback_vec_{i}' for i in range(300)],
                                  index=x_train.index)
feedback_test_df = pd.DataFrame(x_test_feedback_vectors.tolist(), 
                                 columns=[f'feedback_vec_{i}' for i in range(300)],
                                 index=x_test.index)

In [76]:
# Drop original feedback column and concatenate vectors
x_train = x_train.drop('feedback', axis=1)
x_test = x_test.drop('feedback', axis=1)

x_train = pd.concat([x_train, feedback_train_df], axis=1)
x_test = pd.concat([x_test, feedback_test_df], axis=1)

In [77]:
x_train

,region_category_Town,region_category_Village,membership_category_Gold Membership,membership_category_No Membership,membership_category_Platinum Membership,membership_category_Premium Membership,membership_category_Silver Membership,preferred_offer_types_Gift Vouchers/Coupons,preferred_offer_types_Without Offers,medium_of_operation_Desktop,...,feedback_vec_290,feedback_vec_291,feedback_vec_292,feedback_vec_293,feedback_vec_294,feedback_vec_295,feedback_vec_296,feedback_vec_297,feedback_vec_298,feedback_vec_299
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.123372,0.016846,-0.025675,-0.055542,0.046794,0.033285,-0.032552,-0.098674,-0.021484,-0.100259
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.027303,0.129232,-0.270833,0.011597,-0.018565,0.186849,0.010579,-0.024414,0.037304,0.002824
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,-0.009989,-0.032633,-0.133464,-0.115438,-0.023275,-0.009684,0.116699,-0.041748,0.026489,0.055257
3,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.027303,0.129232,-0.270833,0.011597,-0.018565,0.186849,0.010579,-0.024414,0.037304,0.002824
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,-0.123372,0.016846,-0.025675,-0.055542,0.046794,0.033285,-0.032552,-0.098674,-0.021484,-0.100259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23479,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,-0.027303,0.129232,-0.270833,0.011597,-0.018565,0.186849,0.010579,-0.024414,0.037304,0.002824
23480,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,-0.027303,0.129232,-0.270833,0.011597,-0.018565,0.186849,0.010579,-0.024414,0.037304,0.002824
23481,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.168945,0.081868,-0.255859,0.046346,0.070638,0.169271,-0.028646,0.121419,0.068359,-0.111898
23482,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.204102,0.117676,-0.215332,0.051025,0.008057,-0.008301,0.025391,-0.064453,-0.006104,-0.137573
23483,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.168945,0.081868,-0.255859,0.046346,0.070638,0.169271,-0.028646,0.121419,0.068359,-0.111898

In [78]:
from sklearn.preprocessing import StandardScaler
stsc=ColumnTransformer([
    ('std_scaler', StandardScaler(), [col for col in x_train.columns ])
], remainder='passthrough', verbose_feature_names_out=False)
x_train=stsc.fit_transform(x_train)
x_test=stsc.transform(x_test)
columns=stsc.get_feature_names_out()
x_train=pd.DataFrame(x_train,columns=columns)
x_test=pd.DataFrame(x_test,columns=columns)

In [79]:
x_train

,region_category_Town,region_category_Village,membership_category_Gold Membership,membership_category_No Membership,membership_category_Platinum Membership,membership_category_Premium Membership,membership_category_Silver Membership,preferred_offer_types_Gift Vouchers/Coupons,preferred_offer_types_Without Offers,medium_of_operation_Desktop,...,feedback_vec_290,feedback_vec_291,feedback_vec_292,feedback_vec_293,feedback_vec_294,feedback_vec_295,feedback_vec_296,feedback_vec_297,feedback_vec_298,feedback_vec_299
0,-1.066324,-0.382915,-0.473642,-0.512890,-0.361407,-0.37224,-0.441236,-0.722543,1.441055,0.953393,...,-1.234923,-0.854648,1.714041,-0.807391,0.534752,-0.538861,-1.053034,-1.037381,-1.175550,-0.573251
1,-1.066324,-0.382915,-0.473642,-0.512890,-0.361407,-0.37224,-0.441236,-0.722543,1.441055,0.953393,...,-0.460399,1.045920,-1.066306,0.164372,-0.991938,1.154157,-0.317571,-0.073130,0.452195,0.880557
2,-1.066324,-0.382915,-0.473642,-0.512890,-0.361407,-0.37224,-0.441236,1.384000,-0.693936,0.953393,...,-0.320814,-1.691393,0.491611,-1.674321,-1.101955,-1.012583,1.491947,-0.298210,0.152756,1.620033
3,0.937802,-0.382915,-0.473642,1.949736,-0.361407,-0.37224,-0.441236,-0.722543,1.441055,0.953393,...,-0.460399,1.045920,-1.066306,0.164372,-0.991938,1.154157,-0.317571,-0.073130,0.452195,0.880557
4,-1.066324,2.611547,-0.473642,-0.512890,-0.361407,-0.37224,-0.441236,1.384000,-0.693936,0.953393,...,-1.234923,-0.854648,1.714041,-0.807391,0.534752,-0.538861,-1.053034,-1.037381,-1.175550,-0.573251
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23479,-1.066324,2.611547,2.111300,-0.512890,-0.361407,-0.37224,-0.441236,-0.722543,1.441055,0.953393,...,-0.460399,1.045920,-1.066306,0.164372,-0.991938,1.154157,-0.317571,-0.073130,0.452195,0.880557
23480,0.937802,-0.382915,2.111300,-0.512890,-0.361407,-0.37224,-0.441236,1.384000,-0.693936,-1.048886,...,-0.460399,1.045920,-1.066306,0.164372,-0.991938,1.154157,-0.317571,-0.073130,0.452195,0.880557
23481,-1.066324,-0.382915,-0.473642,-0.512890,-0.361407,-0.37224,-0.441236,1.384000,-0.693936,0.953393,...,1.121780,0.244957,-0.896485,0.667333,1.091726,0.960362,-0.986426,1.820502,1.312066,-0.737394
23482,0.937802,-0.382915,-0.473642,-0.512890,2.766966,-0.37224,-0.441236,-0.722543,-0.693936,-1.048886,...,1.405215,0.850496,-0.436863,0.735062,-0.370094,-0.997331,-0.065015,-0.593033,-0.749681,-1.099501
23483,-1.066324,-0.382915,-0.473642,1.949736,-0.361407,-0.37224,-0.441236,-0.722543,1.441055,-1.048886,...,1.121780,0.244957,-0.896485,0.667333,1.091726,0.960362,-0.986426,1.820502,1.312066,-0.737394

In [80]:
# 1. Fix invalid scores (-1) by clipping them to the 1-5 range
y_train = y_train.clip(1, 5)
y_test = y_test.clip(1, 5)

# 2. Shift labels from 1-5 to 0-4 for the Softmax layer
y_train_final = y_train - 1
y_test_final = y_test - 1

In [81]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

model = Sequential([
    # Input Layer: 331 features
    Dense(512, activation='relu', input_shape=(x_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),
    
    # Hidden Layers
    Dense(256, activation='relu'),
    BatchNormalization(),
    Dropout(0.2),
    
    Dense(128, activation='relu'),
    Dropout(0.2),
    
    # Output Layer: 5 neurons for labels 0-4
    Dense(5, activation='softmax')
])

c:\Users\sarth\OneDrive\Documents\MachineLearning Projects\ChurnDetection DeepLearning SupervisedML\venvChurn\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [82]:
model.compile(optimizer='adam', 
              loss='sparse_categorical_crossentropy', 
              metrics=['accuracy'])

In [83]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=8,
    restore_best_weights=True
)

In [84]:
# Execute training
history = model.fit(x_train, y_train_final, 
                    epochs=60, 
                    batch_size=32, 
                    validation_data=(x_test, y_test_final),callbacks=[early_stop])

Epoch 1/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.5457 - loss: 0.9748 - val_accuracy: 0.6348 - val_loss: 0.6905
Epoch 2/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6187 - loss: 0.7380 - val_accuracy: 0.6333 - val_loss: 0.6875
Epoch 3/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6249 - loss: 0.7095 - val_accuracy: 0.6364 - val_loss: 0.6758
Epoch 4/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6288 - loss: 0.7040 - val_accuracy: 0.6419 - val_loss: 0.7027
Epoch 5/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6325 - loss: 0.6991 - val_accuracy: 0.6395 - val_loss: 0.6646
Epoch 6/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6388 - loss: 0.6899 - val_accuracy: 0.6522 - val_loss: 0.6601
Epoch 7/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6428 - loss: 0.6880 - val_accuracy: 0.6496 - val_loss: 0.6627
Epoch 8/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6497 - loss: 0.6805 - val_accuracy: 0.6554 - val_loss: 0.6585
Epoch 9/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6554 - loss: 0.6774 - val_accuracy: 0.6432 - val_loss: 0.7204
Epoch 10/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.6656 - loss: 0.6680 - val_accuracy: 0.6934 - val_loss: 0.6373
Epoch 11/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.6806 - loss: 0.6531 - val_accuracy: 0.7068 - val_loss: 0.6178
Epoch 12/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6895 - loss: 0.6391 - val_accuracy: 0.7067 - val_loss: 0.6050
Epoch 13/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6962 - loss: 0.6320 - val_accuracy: 0.7000 - val_loss: 0.6079
Epoch 14/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7007 - loss: 0.6228 - val_accuracy: 0.7077 - val_loss: 0.5957
Epoch 15/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7044 - loss: 0.6136 - val_accuracy: 0.7207 - val_loss: 0.5698
Epoch 16/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7077 - loss: 0.6054 - val_accuracy: 0.7305 - val_loss: 0.5623
Epoch 17/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7122 - loss: 0.6013 - val_accuracy: 0.7164 - val_loss: 0.5625
Epoch 18/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7118 - loss: 0.5979 - val_accuracy: 0.7362 - val_loss: 0.5558
Epoch 19/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7156 - loss: 0.5904 - val_accuracy: 0.7224 - val_loss: 0.5611
Epoch 20/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7179 - loss: 0.5879 - val_accuracy: 0.7455 - val_loss: 0.5411
Epoch 21/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7180 - loss: 0.5805 - val_accuracy: 0.7320 - val_loss: 0.5345
Epoch 22/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7193 - loss: 0.5766 - val_accuracy: 0.7396 - val_loss: 0.5261
Epoch 23/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7204 - loss: 0.5772 - val_accuracy: 0.7205 - val_loss: 0.5701
Epoch 24/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7225 - loss: 0.5741 - val_accuracy: 0.7524 - val_loss: 0.5155
Epoch 25/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7268 - loss: 0.5663 - val_accuracy: 0.7462 - val_loss: 0.5247
Epoch 26/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7244 - loss: 0.5691 - val_accuracy: 0.7283 - val_loss: 0.5406
Epoch 27/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7230 - loss: 0.5647 - val_accuracy: 0.7382 - val_loss: 0.5477
Epoch 28/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7293 - loss: 0.5627 - val_accuracy: 0.7416 - val_loss: 0.5316
Epoch 29/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7281 - loss: 0.5589 - val_accuracy: 0.7497 - val_loss: 0.5105
Epoch 30/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7306 - loss: 0.5581 - val_accuracy: 0.7419 - val_loss: 0.5163
Epoch 31/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7370 - loss: 0.5532 - val_accuracy: 0.7467 - val_loss: 0.5127
Epoch 32/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7332 - loss: 0.5533 - val_accuracy: 0.7511 - val_loss: 0.5119
Epoch 33/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7383 - loss: 0.5480 - val_accuracy: 0.7494 - val_loss: 0.5098
Epoch 34/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7361 - loss: 0.5473 - val_accuracy: 0.7486 - val_loss: 0.5087
Epoch 35/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7386 - loss: 0.5426 - val_accuracy: 0.7360 - val_loss: 0.5065
Epoch 36/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7395 - loss: 0.5475 - val_accuracy: 0.7550 - val_loss: 0.5137
Epoch 37/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7354 - loss: 0.5487 - val_accuracy: 0.7559 - val_loss: 0.5104
Epoch 38/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7383 - loss: 0.5456 - val_accuracy: 0.7446 - val_loss: 0.5028
Epoch 39/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7361 - loss: 0.5461 - val_accuracy: 0.7569 - val_loss: 0.5120
Epoch 40/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7400 - loss: 0.5411 - val_accuracy: 0.7535 - val_loss: 0.5017
Epoch 41/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7384 - loss: 0.5359 - val_accuracy: 0.7540 - val_loss: 0.4961
Epoch 42/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7408 - loss: 0.5386 - val_accuracy: 0.7579 - val_loss: 0.4969
Epoch 43/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7452 - loss: 0.5382 - val_accuracy: 0.7574 - val_loss: 0.5005
Epoch 44/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7437 - loss: 0.5402 - val_accuracy: 0.7687 - val_loss: 0.4971
Epoch 45/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7447 - loss: 0.5344 - val_accuracy: 0.7632 - val_loss: 0.5021
Epoch 46/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7445 - loss: 0.5350 - val_accuracy: 0.7689 - val_loss: 0.4934
Epoch 47/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7422 - loss: 0.5296 - val_accuracy: 0.7643 - val_loss: 0.4928
Epoch 48/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.7486 - loss: 0.5337 - val_accuracy: 0.7546 - val_loss: 0.5008
Epoch 49/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7473 - loss: 0.5302 - val_accuracy: 0.7622 - val_loss: 0.5014
Epoch 50/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7450 - loss: 0.5317 - val_accuracy: 0.7629 - val_loss: 0.4891
Epoch 51/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7450 - loss: 0.5330 - val_accuracy: 0.7732 - val_loss: 0.4838
Epoch 52/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7464 - loss: 0.5291 - val_accuracy: 0.7498 - val_loss: 0.5012
Epoch 53/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7505 - loss: 0.5285 - val_accuracy: 0.7592 - val_loss: 0.4976
Epoch 54/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7451 - loss: 0.5277 - val_accuracy: 0.7703 - val_loss: 0.4866
Epoch 55/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7506 - loss: 0.5263 - val_accuracy: 0.7655 - val_loss: 0.4918
Epoch 56/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7476 - loss: 0.5272 - val_accuracy: 0.7657 - val_loss: 0.4889
Epoch 57/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7501 - loss: 0.5229 - val_accuracy: 0.7649 - val_loss: 0.4976
Epoch 58/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7519 - loss: 0.5245 - val_accuracy: 0.7572 - val_loss: 0.4909
Epoch 59/60
734/734 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.7485 - loss: 0.5221 - val_accuracy: 0.7621 - val_loss: 0.4973

In [85]:
from sklearn.metrics import classification_report, f1_score, confusion_matrix
import numpy as np

# 1. Get the raw probability predictions
y_pred_probs = model.predict(x_test)

# 2. Convert probabilities to class labels (0-4)
y_pred = np.argmax(y_pred_probs, axis=1)

# 3. Calculate the official HackerEarth Score (Macro F1)
# Note: y_test_final is your shifted 0-4 ground truth
score = 100 * f1_score(y_test_final, y_pred, average="macro")
print(f"HackerEarth Evaluation Score: {score:.2f}")

# 4. Detailed breakdown (Precision, Recall, F1 for each class)
print("\nClassification Report:")
print(classification_report(y_test_final, y_pred, target_names=['Score 1', 'Score 2', 'Score 3', 'Score 4', 'Score 5']))

315/315 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
HackerEarth Evaluation Score: 74.95

Classification Report:
              precision    recall  f1-score   support

     Score 1       0.75      0.58      0.65       990
     Score 2       0.78      0.75      0.76       781
     Score 3       0.89      0.94      0.91      2866
     Score 4       0.76      0.54      0.63      2768
     Score 5       0.69      0.91      0.79      2660

    accuracy                           0.77     10065
   macro avg       0.77      0.75      0.75     10065
weighted avg       0.78      0.77      0.76     10065

In [86]:
from sklearn.metrics import recall_score, precision_score
recall = recall_score(y_test_final, y_pred, average='macro')
precision = precision_score(y_test_final, y_pred, average='macro')
print(f"Recall: {recall:.4f}, Precision: {precision:.4f}")

Recall: 0.7451, Precision: 0.7717